### ISSUE TITLE
TypeError when opening Gallary tab

### ISSUE THREAD

**Issue by RevokedCookie** [TannerReynolds/ShareX-Upload-Server#15]
When opening the gallery tab on the upload server, this Typeerror shows in pm2 logs:

```
5||index    | TypeError: Cannot read property 'includes' of undefined
5|index    |     at ShareXAPI.auth (/root/projects/ShareX-Upload-Server/src/util/auth.js:2:15)
5|index    |     at ShareXAPI.post (/root/projects/ShareX-Upload-Server/src/server/routes/gallery.js:13:15)
5|index    |     at Layer.handle [as handle_request] (/root/projects/ShareX-Upload-Server/node_modules/express/lib/router/layer.js:95:5)
5|index    |     at next (/root/projects/ShareX-Upload-Server/node_modules/express/lib/router/route.js:137:13)
5|index    |     at Route.dispatch (/root/projects/ShareX-Upload-Server/node_modules/express/lib/router/route.js:112:3)
5|index    |     at Layer.handle [as handle_request] (/root/projects/ShareX-Upload-Server/node_modules/express/lib/router/layer.js:95:5)
5|index    |     at /root/projects/ShareX-Upload-Server/node_modules/express/lib/router/index.js:281:22
5|index    |     at Function.process_params (/root/projects/ShareX-Upload-Server/node_modules/express/lib/router/index.js:335:12)
5|index    |     at next (/root/projects/ShareX-Upload-Server/node_modules/express/lib/router/index.js:275:10)
5|index    |     at serveStatic (/root/projects/ShareX-Upload-Server/node_modules/serve-static/index.js:75:16)
```

**Comment by TannerReynolds** [comment]
Try this change 
https://github.com/TannerReynolds/ShareX-Upload-Server/pull/16
