### ISSUE TITLE
Ubuntu 20.04 support

### ISSUE THREAD

**Issue by MrTalon63** [TannerReynolds/ShareX-Upload-Server#44]
**Is your feature request related to a problem? Please describe.**
So I was trying to install it on Ubuntu 20.04 with node _v10.22.0_ but it errored out with 
`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/sharex/img/src/server/app.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`
**Describe the solution you'd like**
Would it work on Node 8 or something?

**Comment by mangosd1337** [comment]
Did you run `npm install`?
If that doesnt work, run `npm install express` and then another `npm install` after it for good measure.

**Comment by TannerReynolds** [comment]
This will be closed by the end of tomorrow if no response is given. It looks like you need to ensure dependencies are installed. With the info we have, this looks like a non-issue
