### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by PadowYT2** [TannerReynolds/ShareX-Upload-Server#95]
**Describe the bug**
```1|cdn-padow |     at Object.<anonymous> (/var/www/cdn-padow/src/server/routes/files.js:2:20)
1|cdn-padow |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
1|cdn-padow |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
1|cdn-padow |     at Module.load (node:internal/modules/cjs/loader:981:32)
1|cdn-padow |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
1|cdn-padow |     at Module.require (node:internal/modules/cjs/loader:1005:19)
1|cdn-padow |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39) {
1|cdn-padow |   code: 'MODULE_NOT_FOUND',
1|cdn-padow |   requireStack: [
1|cdn-padow |     '/var/www/cdn-padow/src/server/routes/files.js',
1|cdn-padow |     '/var/www/cdn-padow/src/server/routes/index.js',
1|cdn-padow |     '/var/www/cdn-padow/src/server/app.js',
1|cdn-padow |     '/var/www/cdn-padow/src/index.js'
1|cdn-padow |   ]
1|cdn-padow | }
```
**To Reproduce**
1. Install fresh version of the upload server
2. Run the script
3. Run the index.js

**Expected behavior**
It should start

**ShareS Version**
4.5.3

**Desktop**
 - OS: Ubuntu 20.04
 - Browser: chrome
 - Version: *don't get it*

**Additional context**
Running `npm i` just gets an another error, even if I'm root and the folder's perms are `-R 777`
```npm ERR! code EPERM
npm ERR! syscall symlink
npm ERR! path ../acorn/bin/acorn
npm ERR! dest /var/www/cdn-padow/node_modules/.bin/acorn
npm ERR! errno -1
npm ERR! Error: EPERM: operation not permitted, symlink '../acorn/bin/acorn' -> '/var/www/cdn-padow/node_modules/.bin/acorn'
npm ERR!  [Error: EPERM: operation not permitted, symlink '../acorn/bin/acorn' -> '/var/www/cdn-padow/node_modules/.bin/acorn'] {
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../acorn/bin/acorn',
npm ERR!   dest: '/var/www/cdn-padow/node_modules/.bin/acorn'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
```

**Comment by PadowYT2** [comment]
Also, #94 could fix it
